name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 05 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: generate readme
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          python3 .github/workflows/wakatime/main.py

      - name: commit readme
        run: |
          git add README.md
          git commit -m '[M] update wakatime stats to readme from workflow'
          git push origin master
