name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 05 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: dependency review 
        uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: true

      - name: generate readme
        uses: actions/checkout@v3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          python3 .github/workflows/wakatime/main.py

      - name: commit readme
        uses: actions/checkout@v3
        run: |
          git add README.md
          git commit -m '[M] update wakatime stats to readme from workflow'
          git push origin master
