name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 05 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: False
          SHOW_TIMEZONE: False
          SHOW_PROJECTS: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_COMMIT: False
          SHOW_LANGUAGE: True
          SHOW_OS: True
          SYMBOL_VERSION: 2
          SHOW_LOC_CHART: False
          COMMIT_MESSAGE: '[M] update from waka-readme-stats workflow'
          SHOW_UPDATED_DATE: False
          SHOW_PROFILE_VIEWS: False
          SHOW_TOTAL_CODE_TIME: False
